language: ruby
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.5.0
env:
  global:
    secure: tTPxM+p8Oz3818KYjGaV9Wzuz2w9PB84+qxUCO0g6yEr92oq93u3f/gl4bCrUV8GIzrKMiJzHLb79MrnsMbfwf/gGgBGMHHoYPytWZj7+Q3Rf/v+tq+MXwmtEf4W40QcZF1tX0rKmoRWLz74zRh8Q16p1mzQBRtByMtB5um5KQ08gANJ9c96mF6TzGD7Cs9YwS6FYIf42f1v0xTAzj3LGROv2/JzhAeHTmd3Vcs7FqZ/6ILKSlgi9bhKpYiVrJU1KlJcQTAll4DgawDorIE7A7L700pM78k9XIPWRztHuVaSZV5nYYJEMZOHRaFVx4kptbbvEtOb6aPLPIV49NR/BEWQcHmakxLeKC8iMhwmxPSJKtaoVby071HkzV2aM25OQBVYgMzOmRWVK8ixE66GcFA/u8G+lZ4bBFfLhm2YMAyF7gZEtBg6aminvmcf1d4CJAt/zKjVD7UbvbJuQPVOpztfI/GxkZcppTbOeLFMHMVSpzpfSsQjvPszaJoiVZuslgt6VWB1ePfgPMyHv94ZcIBByaiWHr3TGjRI5PVOpH7sU7macudVxEKE2t3uwkbBaLPyc8rqvpu37Uaah4SU2VQWRUf40MkUoj2BIgRuRugjsGCUBwdunSmbAaffS4F2ziwY2MNGYr9l4lO00MkDwVrme938RA4hgSNcubMk6v0=
