# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Carlo Veo
description: >- # this means to ignore newlines until "baseurl:"
  This is a personal tech blog for Carlo Veo. My main interests are the Spring Framework specifically Spring Boot and Spring Cloud, Cloud Foundry, microservices architecture, Java
baseurl: "" # the subpath of your site, e.g. /blog
#host: "carlov20.github.io"
#port: "4000"
twitter_username: carlov20
github_username:  carlov20
linkedin_username: carlo-veo-b31a6866
google_analytics: UA-78360858-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - github-pages

asciidoc: {}
asciidoctor: {}

bootstrap:
  assets: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
